import type { Metadata } from "next";

import "@/styles/globals.css";
import { inter } from "@/lib/fonts"
import { NextAuthProvider } from "./next-auth-provider";
import { ReduxProvider } from "./redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ReduxProvider>
          <body className={inter.className}>
            {children}
          </body>
        </ReduxProvider>
      </NextAuthProvider>
    </html>
  );
}
